version: "3.8"
services:
  postgres:
    build:
      dockerfile: docker/postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  application:
    build:
      dockerfile: docker/application
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres
