server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true
      show-sql: true
  liquibase:
    default-schema: effectivemobile